# Generated by Django 4.2 on 2023-06-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='starttingDate',
            new_name='startingDate',
        ),
    ]
