# Generated by Django 4.2 on 2023-06-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_starttingdate_userprofile_startingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='endingDate',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fullAddress',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institute',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='startingDate',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subject',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip',
            field=models.IntegerField(default=''),
        ),
    ]
