# Generated by Django 4.2 on 2023-06-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_userprofile_city_alter_userprofile_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
    ]
